### ISSUE TITLE
Erro ao iniciar os dois projetos simultaneamente.

### ISSUE THREAD

**Issue by johnnyasantoss** [mateusknob/cadastro-pessoas-bludata#1]
Olá!

Ao executar `dotnet run` para iniciar os dois projetos, ocorre um erro devido ao uso da mesma porta (a padrão `:5000`) para os dois projetos.

Isso pode ser resolvido usando o extension method: `UseUrls("http://+:<porta>")` no `Program.cs` na classe `Microsoft.AspNetCore.Hosting.WebHostBuilder`.

That's all!
😄

**Comment by mateusknob** [comment]
Corrigido conforme sugestão, obrigado @johnnyasantoss

**Comment by johnnyasantoss** [comment]
😃
